version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://test_user:test_password@db:5432/restaurant_db
      - DATABASE_TEST_URL=postgres://test_user:test_password@db:5432/restaurant_db
      - SQLX_OFFLINE=true
      - RUST_LOG=debug
      - SOCKETADDRS=0.0.0.0:8080

  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=restaurant_db
    ports:
      - "5432:5432"

volumes:
  pgdata: