///List of 50 popular japanese food items.
pub const FOOD_ITEMS: [&str; 50] = [
    "Sushi",
    "Okonomiyaki",
    "Miso Soup",
    "Yakitori",
    "Udon",
    "Takoyaki",
    "Soba",
    "Sukiyaki",
    "Sashimi",
    "Tofu",
    "Onigiri",
    "Wagashi",
    "Natto",
    "Oden",
    "Shabu Shabu",
    "Tempura",
    "Ramen",
    "Tonkatsu",
    "Kaiseki",
    "Kappo Ryori",
    "Shojin Ryori",
    "Osechi Ryori",
    "Zenzai",
    "Oshiruko",
    "Wagyu",
    "Bento",
    "Omurice",
    "Kiritanpo",
    "Mochi",
    "Gyoza",
    "Shogayaki",
    "Fugu",
    "Gyudon",
    "Karaage",
    "Oyakodon",
    "Robatayaki",
    "Shirasu",
    "Somen",
    "Imagawayaki",
    "Melonpan",
    "Warabimochi",
    "Tamagoyaki",
    "Tsukemono",
    "Yokan",
    "Gyutan",
    "Chankonabe",
    "Anmitsu",
    "Hiyashi chuka",
    "Kushiage",
    "Yatsuhashi",
];
